language: R
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false
sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev


repos:
  CRAN: http://cran.rstudio.com
