dist: trusty

language: R
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false
sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - r-cran-foreach
  - r-cran-copula
  - r-cran-cdvine
  - r-cran-shiny
  - r-cran-tsp

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q

repos:
  CRAN: http://cran.rstudio.com
